{
    'name': 'Business Hub 360° Enterprise Plus',
    'version': '18.0.1.0.0',
    'category': 'Productivity',
    'summary': 'ERP Completo: Finanzas, Inventario, CRM, RRHH, Proyectos, Activos, Gastos y Más',
    'description': 'Modulo multi-tarea que centraliza TODAS las operaciones empresariales',
    'author': 'Soluciones Softhard CA',
    'website': 'https://www.softhard.com',
    'license': 'LGPL-3',
    'depends': [
        'base',
        'web',
        'sale',
        'purchase',
        'stock',
        'account',
        'hr',
        'mail',
        'project',
        'crm',
        'calendar',
    ],
    'data': [
        'security/ir.model.access.csv',
        'data/sequences.xml',
        'data/alert_templates.xml',
        'data/scheduled_actions.xml',
        'data/demo_data.xml',
        'views/dashboard_views.xml',
        'views/financial_views.xml',
        'views/inventory_views.xml',
        'views/document_views.xml',
        'views/asset_views.xml',
        'views/expense_views.xml',
        'views/tickets_views.xml',
        'views/menu_views.xml',
        'wizard/report_wizard_views.xml',
        'report/business_reports.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
    'price': 0,
    'currency': 'USD',
    'images': ['static/description/banner.png'],
    'maintainer': 'Soluciones Softhard CA',
}
