{
    'name': 'Horarios Clan Jiu Jitsu',
    'author': 'Enyelber',
    'website': '',
    'category': 'Sports/Facilities',
    'version': '5.6',
    'icon': '/horarios_clan_jiu_jitsu/static/description/icon.png',
    'depends': ['base', 'web'],
    'data': [
        'security/ir.model.access.csv',
        'data/ai_config_data.xml',
        'wizard/wizards_views.xml',
        'reports/report_horario_area.xml',
        'views/vistas.xml',
        'views/res_config_settings_views.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'horarios_clan_jiu_jitsu/static/src/css/schedule_board.css',
            'horarios_clan_jiu_jitsu/static/src/css/calendar_custom.css',
            'horarios_clan_jiu_jitsu/static/src/css/instructor_kanban.css',
            'horarios_clan_jiu_jitsu/static/src/css/dashboard.css',
            'horarios_clan_jiu_jitsu/static/src/css/ai_sensei.css',
            'horarios_clan_jiu_jitsu/static/src/xml/calendar_popover.xml',
            'horarios_clan_jiu_jitsu/static/src/xml/dashboard.xml',
            'horarios_clan_jiu_jitsu/static/src/xml/ai_sensei.xml',
            'horarios_clan_jiu_jitsu/static/src/js/calendar_controller.js',
            'horarios_clan_jiu_jitsu/static/src/js/gym_dashboard_core.js',
            'horarios_clan_jiu_jitsu/static/src/js/ai_sensei_controller.js',
        ],
    },
    'installable': True,
    'application': True,
}
